### ISSUE TITLE
jskos-convert: table header aliases

### ISSUE THREAD

**Issue by nichtich** [gbv/jskos-cli#37]
To align with https://github.com/n4o-rse/ta4-conservation-dev/issues/2 and similar tools:

- make `parent` an alias for `broaderNotation`
- allow syntax `prefLabel_xx` equivalent to `prefLabel@xx`

Tools differ still in whether and how they build URIs (from identifier, from notation, from label...), this cannot fully be unified.

**Comment by stefandesu** [comment]
Will be included in the next release.
