### ISSUE TITLE
Switch to GitHub workflow for npm deployment

### ISSUE THREAD

**Issue by nichtich** [gbv/jskos-cli#7]
Seems to be broken, using manual publication via `npm publish` as workaround.

**Comment by nichtich** [comment]
See https://travis-ci.com/gbv/jskos-cli/jobs/284105858

**Comment by stefandesu** [comment]
I'd suggest simply switching to a GitHub workflow like we've been doing with our other repositories.

**Comment by stefandesu** [comment]
The workflow is added, but I don't have admin rights on this repo and thus can't add my `NPM_TOKEN` to the repo secrets. I do have publish rights on npm though, so either @nichtich adds his token or he can give me admin rights. ;)
