### ISSUE TITLE
Support reading registry as ndjson

### ISSUE THREAD

**Issue by nichtich** [gbv/jskos-cli#8]
At https://github.com/gbv/jskos-cli/blob/master/bin/jskos-convert#L41 add support of ndjson format.

**Comment by nichtich** [comment]
To convert a kos-registry from ndjson to JSON:

    jq --slurp '{schemes:.}' ../kos-registry/all.ndjson > registry.json

**Comment by stefandesu** [comment]
Decided to go for a very rudimentary, but easy solution here.
